#!/usr/bin/env node
'use strict';

/*
 * scaffold.js: the factory step.
 *
 *   node scaffold.js --name my-app --blocks nav-1,hero-2,features-1,cta-1,footer-b --style geist
 *
 * This is the one place the shared bank (this repo, and the VDS Site Builder Figma file it
 * mirrors) touches a new project. It COPIES - block templates, one token file, a generated
 * manifest - into scaffolds/<name>/, a self-contained tree with no path back to this repo.
 *
 * That is deliberate. VDS is per-project: it derives and proves against ONE project's own
 * globals.css and its own decided-target Figma file, never a shared live dependency (VDS.md
 * S-2, VJS-CC-OPBOX 3). If this script left the new project importing blocks/tokens FROM here
 * at build time, the bank would become a second authority the moment two projects diverged on
 * a block's markup. Instead the new project owns its own copy from the moment it exists, and
 * this script has no further involvement in its life. A factory stamps out a copy and cuts it
 * loose - it does not stay wired into what it made.
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const BLOCKS_DIR = path.join(ROOT, 'blocks');
const TOKENS_DIR = path.join(ROOT, 'tokens');

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith('--')) {
      const key = argv[i].slice(2);
      out[key] = argv[i + 1];
      i++;
    }
  }
  return out;
}

function scaffold({ name, blocks, style, outDir: outDirOverride }) {
  if (!name) throw new Error('--name is required');
  if (!blocks) throw new Error('--blocks is required, e.g. --blocks nav-1,hero-2,footer-a');
  if (!style) throw new Error('--style is required, e.g. --style geist');

  const entries = blocks.split(',').map((s) => s.trim()).filter(Boolean).map((s) => {
    const [type, variant] = s.split(':').length === 2 ? s.split(':') : inferTypeVariant(s);
    return { type, variant };
  });

  // Callers may place the project anywhere; scaffolds/<name> is only the default.
  const outDir = outDirOverride || path.join(ROOT, 'scaffolds', name);
  if (fs.existsSync(outDir)) throw new Error(`${path.relative(ROOT, outDir)} already exists - pick a new name or remove it first`);
  fs.mkdirSync(path.join(outDir, 'blocks'), { recursive: true });
  fs.mkdirSync(path.join(outDir, 'tokens'), { recursive: true });
  fs.mkdirSync(path.join(outDir, 'manifests'), { recursive: true });

  // Copy only the block TYPES actually used - not the whole bank. A new project owns exactly
  // what it asked for, nothing it didn't.
  //
  // ...plus whatever those types require. An ASSEMBLY block (masterdetail) calls its
  // sibling blocks rather than restating their markup, so copying only the named types
  // produced a project that scaffolded clean and then died at build with
  // MODULE_NOT_FOUND on ./objecttable.js. The dependency list is DERIVED by reading the
  // require() calls out of the source, never stored alongside it: a hand-kept list is
  // one more thing that can disagree with the code, and it would disagree silently.
  const typesUsed = collectWithDeps(entries.map((e) => e.type));
  for (const type of typesUsed) {
    const src = path.join(BLOCKS_DIR, `${type}.js`);
    if (!fs.existsSync(src)) throw new Error(`no block type "${type}" in ${BLOCKS_DIR}`);
    fs.copyFileSync(src, path.join(outDir, 'blocks', `${type}.js`));
  }

  // Copy one token file, renamed to tokens/default.json so the new project doesn't inherit
  // the bank's naming - it can rename/edit it freely from day one.
  const tokenSrc = path.join(TOKENS_DIR, `${style}.json`);
  if (!fs.existsSync(tokenSrc)) throw new Error(`no style pack "${style}" in ${TOKENS_DIR}`);
  const tokenData = JSON.parse(fs.readFileSync(tokenSrc, 'utf8'));
  fs.writeFileSync(path.join(outDir, 'tokens', 'default.json'), JSON.stringify(tokenData, null, 2));

  // A copy of the build engine. It is a copy, not a reference - editing it here never touches
  // the bank, and editing the bank never touches this.
  fs.copyFileSync(path.join(ROOT, 'build.js'), path.join(outDir, 'build.js'));

  // A starter manifest wiring the requested blocks in the order given, with placeholder content
  // the new project is expected to replace immediately.
  const manifest = {
    title: name,
    stylePack: 'default',
    page: entries.map((e) => ({ block: e.type, variant: e.variant, content: placeholderContent(e.type) })),
  };
  fs.writeFileSync(path.join(outDir, 'manifests', 'home.json'), JSON.stringify(manifest, null, 2));

  fs.writeFileSync(path.join(outDir, 'README.md'), `# ${name}

Generated by site-factory's scaffold step from the VDS Site Builder bank
(blocks: ${typesUsed.join(', ')}; style pack: ${style}).

This tree is a one-time copy, not a live dependency on the bank. Edit anything here freely
nothing you change can affect the bank, and nothing that changes in the bank later reaches back
into this project. Wire this project's own VDS instance against \`tokens/default.json\` and
whatever you build from \`blocks/\` from here on.

    node build.js manifests/home.json

Replace the placeholder content in manifests/home.json, then this is a real, independent project.
`);

  return { outDir, typesUsed, blockCount: entries.length };
}

/*
 * Walk `require('./x.js')` edges out of the block sources, transitively.
 *
 * Derived, not declared: the answer comes from the same text Node will execute, so it
 * cannot drift from what the file actually needs. Cycles terminate on the `seen` set,
 * and a require of something that is not a sibling block is ignored - only files that
 * live in blocks/ are block dependencies.
 */
function collectWithDeps(types) {
  const seen = new Set();
  const queue = [...new Set(types)];
  while (queue.length) {
    const type = queue.shift();
    if (seen.has(type)) continue;
    seen.add(type);
    const src = path.join(BLOCKS_DIR, `${type}.js`);
    if (!fs.existsSync(src)) continue; // reported by the copy loop, with a better message
    const text = fs.readFileSync(src, 'utf8');
    for (const m of text.matchAll(/require\(['"]\.\/([A-Za-z0-9_-]+)\.js['"]\)/g)) {
      if (!seen.has(m[1])) queue.push(m[1]);
    }
  }
  return [...seen];
}

// Accept a bare variant name ("hero-1", "footer-a") and infer its block type from everything
// before the last hyphen, so callers don't have to type "hero:hero-1" redundantly. Safe because
// no current block type name itself contains a hyphen - if one ever does, pass "type:variant"
// explicitly instead.
function inferTypeVariant(variantName) {
  const idx = variantName.lastIndexOf('-');
  const type = idx === -1 ? variantName : variantName.slice(0, idx);
  return [type, variantName];
}

// Each entry is the UNION of every field any variant of that block type reads from `content`
// (checked against blocks/*.js directly - see git history for the grep). A type's two variants
// often want different shapes (footer-a wants flat `links`, footer-b wants grouped `columns`);
// carrying both means either variant renders clean regardless of which one was requested.
function placeholderContent(type) {
  const company = name_placeholder();
  const PLACEHOLDERS = {
    hero: {
      h1: 'Replace this headline.', sub: 'Replace this subhead.',
      ctaLabel: 'Get started', ctaHref: '#', mediaAlt: 'Placeholder media',
    },
    nav: {
      wordmark: company,
      links: [{ label: 'Product', href: '#' }, { label: 'Docs', href: '#' }, { label: 'Pricing', href: '#' }],
      ctaLabel: 'Sign up', ctaHref: '#',
    },
    footer: {
      wordmark: company, tagline: 'Replace this tagline.', copyright: `© 2026 ${company}`,
      links: [{ label: 'Product', href: '#' }, { label: 'Docs', href: '#' }],
      columns: [{ title: 'Product', links: [{ label: 'Overview', href: '#' }, { label: 'Pricing', href: '#' }] }],
    },
    features: {
      heading: 'Replace this heading.',
      items: [{ title: 'Feature one', body: 'Replace this body copy.' }, { title: 'Feature two', body: 'Replace this body copy.' }],
      columns: ['Free', 'Pro'],
      rows: [{ label: 'Replace this row', values: [true, true] }],
    },
    pricing: {
      heading: 'Pricing',
      plans: [
        { name: 'Free', price: '$0', features: ['Replace this line'], ctaLabel: 'Start free', ctaHref: '#' },
        { name: 'Pro', price: '$0/mo', highlight: true, features: ['Replace this line'], ctaLabel: 'Go Pro', ctaHref: '#' },
      ],
      rows: [{ label: 'Replace this row', values: ['—', '—'] }],
    },
    testimonials: {
      heading: 'What people say',
      items: [{ quote: 'Replace this quote.', name: 'Someone', role: 'Their role' }],
      featured: { quote: 'Replace this quote.', name: 'Someone', role: 'Their role' },
    },
    faq: {
      heading: 'FAQ',
      items: [{ question: 'Replace this question?', answer: 'Replace this answer.' }],
    },
    cta: {
      heading: 'Replace this heading.', sub: 'Replace this subhead.',
      ctaLabel: 'Get started', ctaHref: '#',
      formAction: '#', placeholder: 'Email address',
    },
    sidebar: {
      links: [{ label: 'Overview', href: '#', active: true }, { label: 'Settings', href: '#' }],
      groups: [{ title: 'Workspace', links: [{ label: 'Overview', href: '#', active: true }, { label: 'Settings', href: '#' }] }],
    },
    team: {
      heading: 'Team',
      // `bio` is read by team-2 only. It was missing here, so team-2 rendered the
      // literal string "undefined" into every row - caught by tests/render.test.js
      // on its first run, which is the whole argument for the union rule above.
      people: [
        { name: 'Replace me', role: 'Replace this role', bio: 'Replace this one-line bio.' },
        { name: 'Replace me', role: 'Replace this role', bio: 'Replace this one-line bio.' },
      ],
    },
    contact: {
      heading: 'Get in touch', sub: 'Replace this subhead.', email: 'hello@example.com',
      formAction: '#', ctaLabel: 'Send',
    },
    facetstrip: {
      resultLabel: '24 of 128 records',
      searchAction: '#', searchPlaceholder: 'Filter records',
      facets: [{ label: 'All', active: true, count: 128 }, { label: 'Open', count: 24 }, { label: 'Closed', count: 104 }],
      groups: [{ title: 'Status', facets: [{ label: 'Open', active: true }, { label: 'Closed' }] }, { title: 'Owner', facets: [{ label: 'Me' }, { label: 'Anyone' }] }],
    },
    objecttable: {
      heading: 'Records', meta: '128 total', keyColumn: 'Reference',
      columns: ['Owner', 'Updated'],
      actionLabel: 'Open',
      badgeStyle: 'pill',
      rows: [
        { key: 'REC-0001', cells: ['Replace me', '2 days ago'], status: { label: 'Open', tone: 'info' }, selected: true, href: '#' },
        { key: 'REC-0002', cells: ['Replace me', '5 days ago'], status: { label: 'Closed', tone: 'success' }, href: '#' },
        { key: 'REC-0003', cells: ['Replace me', '1 week ago'], status: { label: 'Blocked', tone: 'danger' }, href: '#' },
      ],
    },
    objectview: {
      kind: 'Record', title: 'REC-0001', sub: 'Replace this subtitle.',
      facts: [
        { label: 'Status', value: 'Open' },
        { label: 'Owner', value: 'Replace me' },
        { label: 'Opened', value: '2 days ago' },
      ],
      actions: [
        { label: 'Edit', href: '#' },
        { label: 'Approve', blocked: true, blockedReason: 'needs a second reviewer' },
      ],
      tabs: [{ label: 'Overview', active: true }, { label: 'Activity', count: 12 }, { label: 'Files', count: 3 }],
    },
    inspector: {
      heading: 'Properties',
      groups: [
        { title: 'Identity', rows: [{ label: 'Reference', value: 'REC-0001' }, { label: 'Kind', value: 'Record' }] },
        { title: 'Ownership', rows: [{ label: 'Owner', value: 'Replace me' }, { label: 'Team', value: 'Replace me' }] },
      ],
      events: [
        { when: '2026-07-30 09:14', what: 'Status set to Open', who: 'replace.me' },
        { when: '2026-07-28 16:02', what: 'Record created', who: 'replace.me' },
      ],
    },
    formfield: {
      heading: 'Details', sub: 'Replace this subhead.', formAction: '#',
      submitLabel: 'Save', cancelLabel: 'Cancel', cancelHref: '#',
      fields: [
        { name: 'name', label: 'Name', type: 'text', required: true, placeholder: 'Replace me' },
        { name: 'email', label: 'Email', type: 'email', required: true, help: 'We only use this to reply.' },
        { name: 'kind', label: 'Kind', type: 'select', options: ['Replace this option', 'And this one'] },
        { name: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Replace this placeholder' },
        // The FIFTH field exists to reach the fifth branch. formfield renders four input
        // shapes and the placeholder exercised three, so `.field__check` was styled by the
        // stylesheet, emitted by the block, and produced by no test - which reads as dead
        // CSS from one end and as covered from the other. A placeholder that skips a branch
        // is a branch nothing renders.
        { name: 'consent', label: 'Email me the write-up', type: 'checkbox' },
      ],
    },
    emptystate: {
      title: 'Nothing here yet.', body: 'Replace this line with what the reader should do first.',
      ctaLabel: 'Create the first one', ctaHref: '#',
      secondaryLabel: 'Read the guide', secondaryHref: '#',
      markAlt: 'Placeholder mark',
      query: 'status:open owner:me',
    },
    pagestate: {
      label: 'Loading', rows: 4,
      code: '500', title: 'That did not load.',
      body: 'Replace this line with what failed and what it means for the reader.',
      retryLabel: 'Try again', retryHref: '#',
      helpLabel: 'Contact support', helpHref: '#',
      reference: 'ref: REPLACE-ME',
    },
    confirmdialog: {
      title: 'Delete this record?', subject: 'REC-0001',
      body: 'Replace this line with what is about to happen.',
      consequence: 'This cannot be undone.',
      typePrompt: 'Type the reference to confirm',
      confirmLabel: 'Delete', confirmHref: '#',
      cancelLabel: 'Cancel', cancelHref: '#',
    },
    // UNION of every field both variants read. A placeholder missing one field prints
    // a literal "undefined" into the page, which is how team-2 shipped a bio-less card.
    toast: {
      body: 'Replace this line with what just happened.',
      dismissLabel: 'Dismiss',
      undoLabel: 'Undo', window: '10 seconds',
    },
    segmentedcontrol: {
      label: 'View', value: 'list',
      items: [
        { label: 'List', value: 'list', href: '#', count: 24 },
        { label: 'Board', value: 'board', href: '#', count: 24 },
        { label: 'Archived', value: 'archived', href: '#', count: 0 },
      ],
    },
    card: {
      title: 'Replace this title', href: '#',
      body: 'Replace this line with a one-sentence summary of the record.',
      badge: 'Open', meta: ['Replace this', 'Replace this'],
      label: 'Replace this label', figure: '0',
      change: 'Replace this with the change and its direction',
      asOf: 'as at a date you replace',
    },
    notfound: {
      code: '404', heading: "This page doesn't exist.", sub: 'Replace this subhead.',
      homeHref: '#', homeLabel: 'Back to home',
      searchAction: '#', searchPlaceholder: 'Search',
    },

    /* The control layer. Each placeholder shows the state that is easiest to get wrong,
       rather than the empty one: a switch that is ON, a checkbox group that is PARTLY
       ticked, a count OVER its cap. A placeholder in the resting state renders a control
       nobody can tell is working. */
    switch: {
      label: 'Replace this setting name', on: true,
      settings: [
        { label: 'Replace this setting name', description: 'Replace this line with what the setting does.', on: true },
        { label: 'Replace this setting name', description: 'Replace this line with what the setting does.', on: false },
      ],
    },
    checkbox: {
      label: 'Replace this label', checked: true, allLabel: 'Select all',
      // Two of three, so the parent renders MIXED. An all-or-nothing placeholder never
      // shows the third state, which is the only reason this block is separate.
      items: [
        { label: 'Replace this option', checked: true },
        { label: 'Replace this option', checked: true },
        { label: 'Replace this option', checked: false },
      ],
    },
    radio: {
      label: 'Replace this question', value: 'one',
      items: [
        { label: 'Replace this option', value: 'one', description: 'Replace this line with what the option means.' },
        { label: 'Replace this option', value: 'two', description: 'Replace this line with what the option means.' },
      ],
    },
    tooltip: {
      label: 'Replace this control name', glyph: 'i',
      targetLabel: 'Replace this label',
      title: 'Replace this title', body: 'Replace this line with the detail the control does not carry.',
    },
    notificationbadge: {
      label: 'Replace this label', srLabel: 'has updates',
      count: 128, cap: 99, unit: 'unread',
    },
    divider: {
      label: 'Replace this label', inset: false,
    },

    /* The four marketing sections the Relume comparison found missing. Each placeholder
       carries the field the block refuses to be vague about: a logo strip's caption (whose
       credibility is being borrowed), a stat's basis (what makes the figure checkable), a
       tile's alt (the brief for an image that does not exist yet), a timeline's date. */
    logolist: {
      caption: 'Replace this with whose logos these are and why',
      heading: 'Replace this heading.',
      total: 'Replace this with the real count',
      logos: [
        { name: 'Replace this', href: '#' }, { name: 'Replace this', href: '#' },
        { name: 'Replace this', href: '#' }, { name: 'Replace this' },
      ],
    },
    stats: {
      heading: 'Replace this heading.',
      body: 'Replace this line with what the figures mean, because a reader will not draw the conclusion themselves.',
      ctaLabel: 'Replace this action', ctaHref: '#',
      stats: [
        { figure: '0', label: 'Replace this label', basis: 'Replace this with how it was measured' },
        { figure: '0', label: 'Replace this label', basis: 'Replace this with how it was measured' },
        { figure: '0', label: 'Replace this label', basis: 'Replace this with how it was measured' },
        { figure: '0', label: 'Replace this label', basis: 'Replace this with how it was measured' },
      ],
    },
    gallery: {
      heading: 'Replace this heading.',
      moreLabel: 'Show more', moreHref: '#',
      items: [
        { alt: 'Replace this with what the image shows', caption: 'Replace this caption', title: 'Replace this title', href: '#' },
        { alt: 'Replace this with what the image shows', caption: 'Replace this caption', title: 'Replace this title', href: '#' },
        { alt: 'Replace this with what the image shows', caption: 'Replace this caption', title: 'Replace this title', href: '#' },
        { alt: 'Replace this with what the image shows', caption: 'Replace this caption', title: 'Replace this title', href: '#' },
      ],
    },
    timeline: {
      heading: 'Replace this heading.',
      entries: [
        { when: '2024', iso: '2024', title: 'Replace this milestone', body: 'Replace this line with what happened.' },
        { when: '2025', iso: '2025', title: 'Replace this milestone', body: 'Replace this line with what happened.' },
        { when: '2026', iso: '2026', title: 'Replace this milestone', body: 'Replace this line with what happened.' },
      ],
    },
    pagination: {
      // Page 4 of 12, so the elision renders on BOTH sides. A placeholder on page 1
      // shows a row that never elides, which is the half of the component that is hard.
      label: 'Pagination', total: 12, current: 4, hrefPattern: '#page=',
      prevHref: '#newer', nextHref: '#older', prevLabel: 'Newer', nextLabel: 'Older',
      caption: 'Ordered by date. There is no page count because the set changes as you read it.',
    },
    pagecontrols: {
      label: 'Pages', count: 7, current: 3,
    },
    menu: {
      label: 'Actions', size: 'small',
      items: [
        { label: 'Replace this action', shortcut: 'R' },
        { label: 'Replace this action', shortcut: 'D' },
        { label: 'Replace this action', disabled: true },
      ],
      groups: [
        { title: 'Replace this group', items: [{ label: 'Replace this action', shortcut: 'R' }, { label: 'Replace this action' }] },
        { title: 'Replace this group', items: [{ label: 'Replace this action' }] },
      ],
      destructive: [{ label: 'Replace this destructive action' }],
    },
    draggablelist: {
      label: 'Order', hint: 'Drag a row, or use the arrow buttons.',
      items: [
        { label: 'Replace this row', meta: 'Replace this detail' },
        { label: 'Replace this row', meta: 'Replace this detail' },
        { label: 'Replace this row', meta: 'Replace this detail' },
      ],
    },
    progressbar: {
      label: 'Replace this label', value: 24, max: 40, unit: 'items', size: 'medium',
    },
    progresssteps: {
      // Step 2 of 3, so all three states render: one done, one current, one to come. A
      // placeholder on step 1 shows two of the three and hides the tick.
      label: 'Progress', current: 2,
      items: [
        { label: 'Replace this step', detail: 'Replace this detail' },
        { label: 'Replace this step', detail: 'Replace this detail' },
        { label: 'Replace this step', detail: 'Replace this detail' },
      ],
    },
    banner: {
      // Warning, because it is the tone whose ink is dark. A placeholder in an
      // easy tone never exercises the per-tone ink that the block exists to carry.
      tone: 'warning',
      headline: 'Replace this headline.',
      body: 'Replace this line with what happened and what it means.',
      actionLabel: 'Replace this action', actionHref: '#',
    },
    systembanner: {
      tone: 'warning',
      message: 'Replace this line with the system-wide state.',
      dismissLabel: 'Dismiss',
      actionLabel: 'Replace this action', actionHref: '#',
    },
    messagecard: {
      heading: 'Replace this heading.',
      body: 'Replace this line with the invitation.',
      actionLabel: 'Replace this action', actionHref: '#',
    },
  };

  // masterdetail is an ASSEMBLY: it calls the other blocks' render functions, so its
  // placeholder nests their placeholders rather than restating their shapes. Restating
  // them would mean fixing the same content twice every time a block's fields change.
  PLACEHOLDERS.masterdetail = {
    facets: PLACEHOLDERS.facetstrip,
    master: PLACEHOLDERS.objecttable,
    detail: PLACEHOLDERS.objectview,
    inspector: PLACEHOLDERS.inspector,
    inspectorVariant: 'properties',
  };

  return PLACEHOLDERS[type] || { note: `Fill in content for block type "${type}" - see blocks/${type}.js for the expected shape.` };
}

function name_placeholder() { return 'Your Company'; }

module.exports = { scaffold, placeholderContent, ROOT, BLOCKS_DIR, TOKENS_DIR };

// Only run as a CLI when invoked directly (`node scaffold.js ...`), not when required
// by wizard.js or anything else that wants scaffold() as a plain function.
if (require.main === module) {
  const args = parseArgs(process.argv.slice(2));
  try {
    const result = scaffold(args);
    console.log(`Scaffolded "${result.blockCount}" blocks (${result.typesUsed.join(', ')}) -> ${path.relative(ROOT, result.outDir)}`);
    console.log(`cd ${path.relative(process.cwd(), result.outDir)} && node build.js manifests/home.json`);
  } catch (err) {
    console.error(`scaffold failed: ${err.message}`);
    process.exit(1);
  }
}
