#!/usr/bin/env node
'use strict';

/*
 * scaffold.js: the factory step.
 *
 *   node scaffold.js --name my-app --blocks nav-1,hero-2,features-1,cta-1,footer-b --style geist
 *
 * This is the one place the shared bank (this repo, and the VDS Site Builder Figma file it
 * mirrors) touches a new project. It COPIES — block templates, one token file, a generated
 * manifest — into scaffolds/<name>/, a self-contained tree with no path back to this repo.
 *
 * That is deliberate. VDS is per-project: it derives and proves against ONE project's own
 * globals.css and its own decided-target Figma file, never a shared live dependency (VDS.md
 * S-2, VJS-CC-OPBOX 3). If this script left the new project importing blocks/tokens FROM here
 * at build time, the bank would become a second authority the moment two projects diverged on
 * a block's markup. Instead the new project owns its own copy from the moment it exists, and
 * this script has no further involvement in its life. A factory stamps out a copy and cuts it
 * loose — it does not stay wired into what it made.
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const BLOCKS_DIR = path.join(ROOT, 'blocks');
const TOKENS_DIR = path.join(ROOT, 'tokens');

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith('--')) {
      const key = argv[i].slice(2);
      out[key] = argv[i + 1];
      i++;
    }
  }
  return out;
}

function scaffold({ name, blocks, style }) {
  if (!name) throw new Error('--name is required');
  if (!blocks) throw new Error('--blocks is required, e.g. --blocks nav-1,hero-2,footer-a');
  if (!style) throw new Error('--style is required, e.g. --style geist');

  const entries = blocks.split(',').map((s) => s.trim()).filter(Boolean).map((s) => {
    const [type, variant] = s.split(':').length === 2 ? s.split(':') : inferTypeVariant(s);
    return { type, variant };
  });

  const outDir = path.join(ROOT, 'scaffolds', name);
  if (fs.existsSync(outDir)) throw new Error(`scaffolds/${name} already exists — pick a new name or remove it first`);
  fs.mkdirSync(path.join(outDir, 'blocks'), { recursive: true });
  fs.mkdirSync(path.join(outDir, 'tokens'), { recursive: true });
  fs.mkdirSync(path.join(outDir, 'manifests'), { recursive: true });

  // Copy only the block TYPES actually used — not the whole bank. A new project owns exactly
  // what it asked for, nothing it didn't.
  const typesUsed = [...new Set(entries.map((e) => e.type))];
  for (const type of typesUsed) {
    const src = path.join(BLOCKS_DIR, `${type}.js`);
    if (!fs.existsSync(src)) throw new Error(`no block type "${type}" in ${BLOCKS_DIR}`);
    fs.copyFileSync(src, path.join(outDir, 'blocks', `${type}.js`));
  }

  // Copy one token file, renamed to tokens/default.json so the new project doesn't inherit
  // the bank's naming — it can rename/edit it freely from day one.
  const tokenSrc = path.join(TOKENS_DIR, `${style}.json`);
  if (!fs.existsSync(tokenSrc)) throw new Error(`no style pack "${style}" in ${TOKENS_DIR}`);
  const tokenData = JSON.parse(fs.readFileSync(tokenSrc, 'utf8'));
  fs.writeFileSync(path.join(outDir, 'tokens', 'default.json'), JSON.stringify(tokenData, null, 2));

  // A copy of the build engine. It is a copy, not a reference — editing it here never touches
  // the bank, and editing the bank never touches this.
  fs.copyFileSync(path.join(ROOT, 'build.js'), path.join(outDir, 'build.js'));

  // A starter manifest wiring the requested blocks in the order given, with placeholder content
  // the new project is expected to replace immediately.
  const manifest = {
    title: name,
    stylePack: 'default',
    page: entries.map((e) => ({ block: e.type, variant: e.variant, content: placeholderContent(e.type) })),
  };
  fs.writeFileSync(path.join(outDir, 'manifests', 'home.json'), JSON.stringify(manifest, null, 2));

  fs.writeFileSync(path.join(outDir, 'README.md'), `# ${name}

Generated by site-factory's scaffold step from the VDS Site Builder bank
(blocks: ${typesUsed.join(', ')}; style pack: ${style}).

This tree is a one-time copy, not a live dependency on the bank. Edit anything here freely —
nothing you change can affect the bank, and nothing that changes in the bank later reaches back
into this project. Wire this project's own VDS instance against \`tokens/default.json\` and
whatever you build from \`blocks/\` from here on.

    node build.js manifests/home.json

Replace the placeholder content in manifests/home.json, then this is a real, independent project.
`);

  return { outDir, typesUsed, blockCount: entries.length };
}

// Accept a bare variant name ("hero-1", "footer-a") and infer its block type from everything
// before the last hyphen, so callers don't have to type "hero:hero-1" redundantly. Safe because
// no current block type name itself contains a hyphen — if one ever does, pass "type:variant"
// explicitly instead.
function inferTypeVariant(variantName) {
  const idx = variantName.lastIndexOf('-');
  const type = idx === -1 ? variantName : variantName.slice(0, idx);
  return [type, variantName];
}

// Each entry is the UNION of every field any variant of that block type reads from `content`
// (checked against blocks/*.js directly — see git history for the grep). A type's two variants
// often want different shapes (footer-a wants flat `links`, footer-b wants grouped `columns`);
// carrying both means either variant renders clean regardless of which one was requested.
function placeholderContent(type) {
  const company = name_placeholder();
  const PLACEHOLDERS = {
    hero: {
      h1: 'Replace this headline.', sub: 'Replace this subhead.',
      ctaLabel: 'Get started', ctaHref: '#', mediaAlt: 'Placeholder media',
    },
    nav: {
      wordmark: company,
      links: [{ label: 'Product', href: '#' }, { label: 'Docs', href: '#' }, { label: 'Pricing', href: '#' }],
      ctaLabel: 'Sign up', ctaHref: '#',
    },
    footer: {
      wordmark: company, tagline: 'Replace this tagline.', copyright: `© 2026 ${company}`,
      links: [{ label: 'Product', href: '#' }, { label: 'Docs', href: '#' }],
      columns: [{ title: 'Product', links: [{ label: 'Overview', href: '#' }, { label: 'Pricing', href: '#' }] }],
    },
    features: {
      heading: 'Replace this heading.',
      items: [{ title: 'Feature one', body: 'Replace this body copy.' }, { title: 'Feature two', body: 'Replace this body copy.' }],
      columns: ['Free', 'Pro'],
      rows: [{ label: 'Replace this row', values: [true, true] }],
    },
    pricing: {
      heading: 'Pricing',
      plans: [
        { name: 'Free', price: '$0', features: ['Replace this line'], ctaLabel: 'Start free', ctaHref: '#' },
        { name: 'Pro', price: '$0/mo', highlight: true, features: ['Replace this line'], ctaLabel: 'Go Pro', ctaHref: '#' },
      ],
      rows: [{ label: 'Replace this row', values: ['—', '—'] }],
    },
    testimonials: {
      heading: 'What people say',
      items: [{ quote: 'Replace this quote.', name: 'Someone', role: 'Their role' }],
      featured: { quote: 'Replace this quote.', name: 'Someone', role: 'Their role' },
    },
    faq: {
      heading: 'FAQ',
      items: [{ question: 'Replace this question?', answer: 'Replace this answer.' }],
    },
    cta: {
      heading: 'Replace this heading.', sub: 'Replace this subhead.',
      ctaLabel: 'Get started', ctaHref: '#',
      formAction: '#', placeholder: 'Email address',
    },
    sidebar: {
      links: [{ label: 'Overview', href: '#', active: true }, { label: 'Settings', href: '#' }],
      groups: [{ title: 'Workspace', links: [{ label: 'Overview', href: '#', active: true }, { label: 'Settings', href: '#' }] }],
    },
    team: {
      heading: 'Team',
      people: [{ name: 'Replace me', role: 'Replace this role' }, { name: 'Replace me', role: 'Replace this role' }],
    },
    contact: {
      heading: 'Get in touch', sub: 'Replace this subhead.', email: 'hello@example.com',
      formAction: '#', ctaLabel: 'Send',
    },
    notfound: {
      code: '404', heading: "This page doesn't exist.", sub: 'Replace this subhead.',
      homeHref: '#', homeLabel: 'Back to home',
      searchAction: '#', searchPlaceholder: 'Search',
    },
  };
  return PLACEHOLDERS[type] || { note: `Fill in content for block type "${type}" — see blocks/${type}.js for the expected shape.` };
}

function name_placeholder() { return 'Your Company'; }

module.exports = { scaffold, placeholderContent, ROOT, BLOCKS_DIR, TOKENS_DIR };

// Only run as a CLI when invoked directly (`node scaffold.js ...`), not when required
// by wizard.js or anything else that wants scaffold() as a plain function.
if (require.main === module) {
  const args = parseArgs(process.argv.slice(2));
  try {
    const result = scaffold(args);
    console.log(`Scaffolded "${result.blockCount}" blocks (${result.typesUsed.join(', ')}) -> ${path.relative(ROOT, result.outDir)}`);
    console.log(`cd ${path.relative(process.cwd(), result.outDir)} && node build.js manifests/home.json`);
  } catch (err) {
    console.error(`scaffold failed: ${err.message}`);
    process.exit(1);
  }
}
